/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemandaRouteImport } from './routes/demanda'
import { Route as ProducaoRouteImport } from './routes/producao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandaRoute = DemandaRouteImport.update({
  id: '/demanda',
  path: '/demanda',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducaoRoute = ProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demanda': typeof DemandaRoute
  '/producao': typeof ProducaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demanda': typeof DemandaRoute
  '/producao': typeof ProducaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demanda': typeof DemandaRoute
  '/producao': typeof ProducaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demanda' | '/producao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demanda' | '/producao'
  id: '__root__' | '/' | '/demanda' | '/producao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemandaRoute: typeof DemandaRoute
  ProducaoRoute: typeof ProducaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demanda': {
      id: '/demanda'
      path: '/demanda'
      fullPath: '/demanda'
      preLoaderRoute: typeof DemandaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producao': {
      id: '/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof ProducaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemandaRoute: DemandaRoute,
  ProducaoRoute: ProducaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
